version: '2'
services:
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: 10.0.75.1
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  react:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - python
    links:
      - python
    environment:
      API: http://python:80
    ports:
      - "8443:8443"
